[package]
name = "twitchbot"
version = "0.1.0"
authors = ["yi <rs@neb.best>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex="1"
hexdump = "0.1.0"